CREATE DATABASE IF NOT EXISTS wall_signatures;
CREATE DATABASE IF NOT EXISTS api_info;
CREATE DATABASE IF NOT EXISTS operator;
CREATE DATABASE IF NOT EXISTS go_auth;
CREATE DATABASE IF NOT EXISTS yeti_studio;
CREATE DATABASE IF NOT EXISTS quantum_auth;

CREATE USER IF NOT EXISTS idfi_app;
CREATE USER IF NOT EXISTS operator_app;
CREATE USER IF NOT EXISTS node_mailer_app;
CREATE USER IF NOT EXISTS go_auth_app;
CREATE USER IF NOT EXISTS yeti_app;
CREATE USER IF NOT EXISTS quantum_auth_service;

GRANT ALL ON DATABASE wall_signatures TO idfi_app WITH GRANT OPTION;
GRANT ALL ON DATABASE operator TO operator_app WITH GRANT OPTION;
GRANT ALL ON DATABASE api_info TO node_mailer_app WITH GRANT OPTION;
GRANT ALL ON DATABASE go_auth TO go_auth_app WITH GRANT OPTION;
GRANT ALL ON DATABASE yeti_studio TO yeti_app WITH GRANT OPTION;
GRANT ALL ON DATABASE quantum_auth TO quantum_auth_service WITH GRANT OPTION;

