CREATE DATABASE IF NOT EXISTS wall_signatures;
CREATE DATABASE IF NOT EXISTS api_info;
CREATE DATABASE IF NOT EXISTS operator;

CREATE USER IF NOT EXISTS idfi_app;
CREATE USER IF NOT EXISTS operator_app;
CREATE USER IF NOT EXISTS node_mailer_app;
GRANT ALL ON DATABASE wall_signatures TO idfi_app WITH GRANT OPTION;
GRANT ALL ON DATABASE operator TO operator_app WITH GRANT OPTION;
GRANT ALL ON DATABASE api_info TO node_mailer_app WITH GRANT OPTION;
