CREATE DATABASE IF NOT EXISTS wall_signatures;
CREATE DATABASE IF NOT EXISTS operator;
CREATE USER IF NOT EXISTS idfi_app;
CREATE USER IF NOT EXISTS operator_app;
GRANT ALL ON DATABASE wall_signatures TO idfi_app WITH GRANT OPTION;
GRANT ALL ON DATABASE operator TO operator_app WITH GRANT OPTION;